BOARD_WIDTH = 40
BOARD_HEIGHT = 60
CELL_SIZE = 20
SCREEN_WIDTH = BOARD_WIDTH * CELL_SIZE
SCREEN_HEIGHT = BOARD_HEIGHT * CELL_SIZE

PLAYER_START = [(SCREEN_WIDTH // 4), SCREEN_HEIGHT // 2]

COLORS = {
    "background": (0, 0, 0),
    "player1": (28, 255, 51),
    "player2": (255, 135, 28)
}